### PR TITLE
Bump to 3.3.0

### PR DESCRIPTION
**Pull request by RaulPPelaez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Closes #18

### CODE REVIEW

**Comment by RaulPPelaez** [comment]
This runs out of time **by far**. At 6h it has only compiled around 26%.
@h-vetinari, is there a way for me to provide the artifacts from a local build?

**Comment by RaulPPelaez** [comment]
Another possibility is to provide the build in header-only mode.

**Comment by h-vetinari** [comment]
> @h-vetinari, is there a way for me to provide the artifacts from a local build?

Yes, check out [CFEP-03](https://github.com/conda-forge/cfep/blob/main/cfep-03.md).

> Another possibility is to provide the build in header-only mode.

Another possibility is to use the new self-hosted bigger runners, as in https://github.com/conda-forge/pytorch-cpu-feedstock/pull/210 ([overview](https://github.com/Quansight/open-gpu-server); ignore the refactoring in that PR, that's unrelated to where things run, except in the sense that we could use a more advantageous build style by doing it all in one giant build; relevant changes are in `conda-forge.yml`).

I think cutlass would actually be a very reasonable candidate for this, so this would be my preferred solution actually. Would you be up to give this a shot?

**Comment by RaulPPelaez** [comment]
Lets go with the big runners then.
I opened a few PRs:
1. Admin request to include cutlass in the list of feedstocks allowed to run in openstack https://github.com/conda-forge/admin-requests/pull/945
2. Add myself as a maintainer of cutlass https://github.com/conda-forge/cutlass-feedstock/pull/20
3. Add myself to the list of allowed openstack users https://github.com/Quansight/open-gpu-server/pull/27

**Comment by RaulPPelaez** [comment]
I pushed the changes required to run in the self-hoster runners, not sure if I got it right, though.

**Comment by h-vetinari** [comment]
Cool, happy to hear it!

We'll have to wait for a PR from the bot after the admin-requests PR, but in any case, once you rebase, please remove https://github.com/conda-forge/cutlass-feedstock/pull/19/commits/65c856dd9e4096c388316c0a0060b081a075e6a9, it's not necessary (anymore).

**Comment by RaulPPelaez** [comment]
@conda-forge-admin, please rerender

**Comment by RaulPPelaez** [comment]
@conda-forge-admin, please rerender

**Comment by leofang** [comment]
Q: What's the status here? Is there anything I can help with?

**Comment by leofang** [comment]
TBH I am very confused. CUTLASS like CCCL is a header-only template library, why are we setting `CUTLASS_ENABLE_LIBRARY=ON` and making our lives so hard here...? Ideally, we should just instruct CMake to copy the headers to the right place. Right now we hit a ton of CI issues here, and also making the resulting package very large in size, without obvious benefit.

**Comment by leofang** [comment]
Thanks very much for all the efforts and sorry for the struggling. Now that we restored `cutlass` as a header-only package (#22) and also released 3.3.0 (#24), this PR is no longer needed. Let me proceed and close it.

**Pull request closed without merging**
